name: Docker API Builds

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Check out repository
      - uses: actions/checkout@v2
    
      - name: Deploy to Heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: ${{secrets.GENERATE_TEST_API_KEY}}
          heroku_app_name: "generate-test-service" 
          heroku_email: "zacktaylor159@gmail.com"
          remote_branch: "main"
          usedocker: true
          appdir: "generate-test-service"
